export const projectData = [
  {
    slug: "vincitore-sky",
    title: "Vincitore Sky",
    location: "Hanspura",
    category: ["residential", "commercial"],
    interest: ["Buy", "Invest", "Lease"],
    type: ["3bhk", "4bhk", "showrooms", "shop"],
    fullAddress:
      "Vincitore Sky, near Anante Saure Complex, opposite Sarthi Bungalows, Hanspura, Ahmedabad, 382330",
    category_title_1: "Flat",
    category_price_1: "1.03* Cr.",
    category_size_1: "294 to 416 sq. yards",
    category_title_2: "Shop",
    category_price_2: "50* Lakh",
    category_size_2: "736 to 2619 sq. ft",
    imageUrl: "/projects/vincitore-sky/VincitoreSky-2.jpeg",
    review: "4.4",
    status: "Ready To Move",
    link: "https://www.google.com/maps/embed?...",
  },
  {
    slug: "vincitore-rivera",
    title: "Vincitore Rivera",
    location: "New Vastral",
    category: ["residential", "commercial"],
    interest: ["Buy", "Invest", "Lease"],
    type: ["3bhk", "shop"],
    fullAddress:
      "Vincitore Rivera, Near Dwarkesh Farm, Vastral, Ahmedabad, 382418",
    category_title_1: "Flat",
    category_price_1: "65* Lakh.",
    category_size_1: "221 to 238 sq. yards",
    category_title_2: "Shop",
    category_price_2: "50* Lakh",
    category_size_2: "444 to 2064 sq. ft",
    imageUrl: "/projects/vincitore-rivera/VincitoreRivera-7.jpeg",
    review: "4.9",
    status: "Under Construction",
    link: "https://www.google.com/maps/embed?...",
  },
  {
    slug: "vincitore-vintage",
    title: "Vincitore Vintage",
    location: "New Vastral",
    interest: ["Buy", "Invest", "Lease"],
    type: ["3bhk", "shop"],
    fullAddress:
      "Vincitore Vintage, Opposite Shyamasi Farm, near Madhav Farm, Vastral, Ahmedabad, 382418",
    category_title_1: "Flat",
    category_price_1: "75.55* Lakh",
    category_size_1: "231 sq. yards",
    category_title_2: "Shop",
    category_price_2: "60* Lakh",
    category_size_2: "506 to 3255 sq. ft",
    imageUrl: "/projects/vincitore-vintage/VincitoreVintage-3.jpg",
    review: "5.0",
    status: "Under Construction",
    link: "https://www.google.com/maps/embed?...",
  },
  {
    slug: "vincitore-valley",
    title: "Vincitore Valley",
    location: "Hathijan",
    category: ["residential", "commercial"],
    interest: ["Buy", "Invest", "Lease"],
    type: ["2bhk", "3bhk", "shop"],
    fullAddress:
      "Vincitore Valley, Opp. Dharm Villa Bunglows, Nr. Divine School, Hathijan Circle, SP Ring Road, Hathijan, Ahmedabad, 382445",
    category_title_1: "Flat",
    category_price_1: "38* Lakh",
    category_size_1: "152 to 214 sq. yards",
    category_title_2: "Shop",
    category_price_2: "35* Lakh",
    category_size_2: "320 to 2772 sq. ft",
    imageUrl: "/projects/vincitore-valley/VincitoreValley-3.jpg",
    review: "4.9",
    status: "Under Construction",
    link: "https://www.google.com/maps/embed?...",
  },
  {
    slug: "the-7-vincitore",
    title: "The 7 Vincitore",
    location: "New Vatva",
    category: ["residential", "commercial"],
    interest: ["Buy", "Invest", "Lease"],
    type: ["2bhk", "3bhk", "shop"],
    fullAddress:
      "The 7 Vincitore, opposite Agriculture Karmavati Market, near D-Mart, New Vatva, Ahmedabad, 382440",
    category_title_1: "Flat",
    category_price_1: "35.26* Lakh",
    category_size_1: "164 to 242 sq. yards",
    category_title_2: "Shop",
    category_price_2: "50* Lakh",
    category_size_2: "400 to 1086 sq. ft",
    imageUrl: "/projects/the-7-vincitore/The7Vincitore-2.jpeg",
    review: "4.8",
    status: "Comming Soon",
    link: "https://www.google.com/maps/embed?...",
  },
  {
    slug: "shivalay-bungalows",
    title: "Shivalay Bungalows",
    location: "Naroda Dehgam Highway, Raipur",
    category: ["residential", "commercial"],
    interest: ["Buy", "Invest", "Lease"],
    type: ["5bhk"],
    fullAddress:
      "Shivalay Bungalows, Narmada Canal, opposite subham farm, Naroda Dehgam Highway, Raipur",
    category_title_1: "Bungalows",
    category_price_1: "3.50* Cr",
    category_size_1: "478 to 1389 sq. yards",
    category_title_2: "Bungalows",
    category_price_2: null,
    category_size_2: "668 to 842 sq. yards",
    imageUrl: "/projects/shivalay-bunglols/ShivalayBunglols-2.jpg",
    review: "4.8",
    status: "Comming Soon",
    link: "https://www.google.com/maps/embed?...",
  },
];
